export const aboutMeTranslations = {
    "es": {
        "title": "Acerca de Mí",
        "text": "<p>¡Hola! Me llamo <span class='text-pink-600'>Iñaqui Paladino Bravo</span>, tengo <span class='text-pink-600'>23 años</span> y soy de Tandil, Buenos Aires, Argentina.</p><p>Soy <span class='text-pink-600'>Ingeniero de Sistemas</span> especializado en <span class='text-pink-600'>backend</span> y <span class='text-pink-600'>arquitecturas cloud-native</span>. Tengo experiencia en el diseño y despliegue de sistemas <span class='text-pink-600'>orientados a eventos en AWS</span> utilizando Infraestructura como Código (IaC) y patrones serverless, con un fuerte enfoque en la confiabilidad, la observabilidad y la eficiencia de costos.</p><p>Actualmente diseño y opero sistemas backend que procesan <span class='text-pink-600'>grandes volúmenes de datos</span> para la automatización y <span class='text-pink-600'>toma de decisiones</span>. Cuento con una mirada integral sobre el ciclo de vida del software, participando activamente desde el análisis de requerimientos hasta la implementación y soporte en entornos productivos.</p><p>Busco crecer en entornos de ingeniería de alto rendimiento y buena <span class='text-pink-600'>cultura</span>, donde la profundidad técnica y el <span class='text-pink-600'>ownership</span> sean valores clave para construir soluciones robustas.</p>"
    },

    "en": {
        "title": "About Me",
        "text": "<p>Hi! My name is <span class='text-pink-600'>Iñaqui Paladino Bravo</span>, I'm <span class='text-pink-600'>23 years old</span>, and I'm from Tandil, Buenos Aires, Argentina.</p><p>I am a <span class='text-pink-600'>Systems Engineer</span> specializing in <span class='text-pink-600'>backend</span> and <span class='text-pink-600'>cloud-native architectures</span>. I have experience designing and deploying <span class='text-pink-600'>event-driven systems on AWS</span> using Infrastructure as Code (IaC) and serverless patterns, with a strong focus on reliability, observability, and cost-efficiency.</p><p>Currently, I design and operate backend systems that process <span class='text-pink-600'>large volumes of data</span> for automation and <span class='text-pink-600'>decision-making</span>. I possess a holistic view of the software lifecycle, actively participating from requirements analysis to implementation and support in production environments.</p><p>I am looking to grow in high-performance engineering environments with a strong <span class='text-pink-600'>culture</span>, where technical depth and <span class='text-pink-600'>ownership</span> are core values for building robust solutions.</p>"
    }
}
