export const aboutMeTranslations = {
    "es": {
        "title": "Acerca de Mí",
        "text": "<p>¡Hola! Me llamo <span class='text-pink-600'>Iñaqui Paladino Bravo</span>, tengo <span class='text-pink-600'>23 años</span> y soy de Tandil, Buenos Aires, Argentina. Desde chico me apasiona el mundo de las computadoras, y fue esa curiosidad la que me llevó a aprender mi primer lenguaje de programación: <span class='text-pink-600'>C</span>, escribiendo juegos simples de consola. Recientemente finalicé la carrera de <span class='text-pink-600'>Ingeniería de Sistemas</span> en la UNICEN, donde me formé con una fuerte base en <span class='text-pink-600'>diseño y arquitectura de sistemas</span>, y desarrollé una mirada integral sobre cómo construir soluciones tecnológicas robustas. He trabajado en equipos de desarrollo con metodologías ágiles como <span class='text-pink-600'>Scrum</span> y <span class='text-pink-600'>SAFe</span>, usando herramientas como <span class='text-pink-600'>Jira</span>, <span class='text-pink-600'>Trello</span> y <span class='text-pink-600'>Git</span>. Me interesa construir software útil, bien estructurado y orientado al usuario, y actualmente estoy profundizando mi experiencia en procesamiento de datos, automatización de procesos y desarrollo de soluciones backend orientadas a la toma de decisiones. Mi capacidad de adaptación y atención a los detalles me ayudan a enfrentar nuevos desafíos con confianza y a mantener un enfoque constante en el aprendizaje y la mejora continua</p>",
    },

    "en": {
        "title": "About Me",
        "text": "<p>Hi! My name is <span class='text-pink-600'>Iñaqui Paladino Bravo</span>, I’m <span class='text-pink-600'>23 years old</span> and I’m from Tandil, Buenos Aires, Argentina. I’ve been passionate about computers since I was a kid, and that curiosity led me to learn my first programming language: <span class='text-pink-600'>C</span>, by writing simple console games. I recently graduated with a degree in <span class='text-pink-600'>Systems Engineering</span> from UNICEN, where I built a strong foundation in <span class='text-pink-600'>system design and architecture</span>, and developed a comprehensive perspective on how to build robust technological solutions. I’ve worked on development teams using agile methodologies such as <span class='text-pink-600'>Scrum</span> and <span class='text-pink-600'>SAFe</span>, and tools like <span class='text-pink-600'>Jira</span>, <span class='text-pink-600'>Trello</span>, and <span class='text-pink-600'>Git</span>. I’m passionate about building useful, well-structured, and user-centered software, and I’m currently expanding my experience in data processing, process automation, and backend solutions focused on decision-making. My adaptability and attention to detail help me face new challenges with confidence and stay focused on continuous learning and improvement.</p>"
    }
}
