export const aboutMeTranslations = {
    "es": {
        "title": "Acerca de Mí",
        "text": "<p>¡Hola! Me llamo <span class='text-pink-600'>Iñaqui Paladino Bravo</span>, tengo <span class='text-pink-600'>22 años</span> y vivo en la ciudad de Tandil, provincia de Buenos Aires, Argentina. Desde muy chico me intereso el mundo de las computadoras y comprender tanto su software como su hardware. Esto me llevó en mi adolescencia a aprender mi primer lenguaje de programación: <span class='text-pink-600'>C</span>, con el que comenze escribiendo juegos simples de consola. Actualmente, estoy finalizando la carrera de <span class='text-pink-600'>Ingeniería de Sistemas</span> en la UNICEN, donde me queda terminar y presentar mi tesis para culminar mis estudios.</p> <p>A lo largo de mi formación, he adquirido una sólida base en el <span class='text-pink-600'>diseño y arquitectura de sistemas</span>, enfocándome en comprender la <span class='text-pink-600 italic'>big picture</span> de los sistemas. Esto me permite analizar y estructurar soluciones eficaces que integran diversos componentes tecnológicos. He trabajado en equipos de desarrollo utilizando metodologías ágiles como <span class='text-pink-600'>Scrum</span> y <span class='text-pink-600'>SAFe</span>, manejando herramientas de gestión como <span class='text-pink-600'>Jira</span> y <span class='text-pink-600'>Trello</span>, y colaborando en la gestión de código con <span class='text-pink-600'>Git</span>.</p> <p>Complementando mis habilidades técnicas, también he desarrollado habilidades blandas como la <span class='text-pink-600'>comunicación efectiva</span>, la <span class='text-pink-600'>colaboración en equipo</span>, y la <span class='text-pink-600'>resolución de problemas</span>. Mi capacidad de adaptación y atención a los detalles me ayudan a enfrentar nuevos desafíos con confianza y a mantener un enfoque constante en el aprendizaje y la mejora continua.</p>"
    },

    "en": {
        "title": "About Me",
        "text": "<p>Hello! I am <span class='text-pink-600'>Iñaqui Paladino Bravo</span>, I am <span class='text-pink-600'>22 years old</span> and live in the city of Tandil, Buenos Aires, Argentina. Since I was a child, I have been interested in the world of computers and understand both their software and their hardware. This led me in my teens to learn my first programming language: <span class='text-pink-600'>C</span>, with which I started writing simple console games. Currently, I am finishing my degree in <span class='text-pink-600'>Systems Engineering</span> at UNICEN, where I have to finish and present my thesis to complete my studies.</p> <p>Throughout my training, I have acquired a solid foundation in <span class='text-pink-600'>system design and architecture</span>, focusing on understanding the <span class='text-pink-600 italic'>big picture</span> of systems. This enables me to analyze and structure effective solutions that integrate various technological components. I have worked in development teams using agile methodologies such as <span class='text-pink-600'>Scrum</span> and <span class='text-pink-600'>SAFe</span>, handling management tools like <span class='text-pink-600'>Jira</span> and <span class='text-pink-600'>Trello</span>, and collaborating on code management with <span class='text-pink-600'>Git</span>.</p> <p>Complementing my technical skills, I have also developed soft skills such as <span class='text-pink-600'>effective communication</span>, <span class='text-pink-600'>team collaboration</span>, and <span class='text-pink-600'>problem-solving</span>. My adaptability and attention to detail help me face new challenges with confidence and maintain a constant focus on learning and continuous improvement.</p>"
    }
}
